#!/usr/bin/env lua

local args = {...}
local day = args[1]
if string.len(day) < 2 then 
    day = "0" .. day
end

local file_utils = require('src.utils.file')

local solver = require("src.day." .. day)

local input = file_utils.lines_from_file("input/" .. day .. ".txt")
local test_input = file_utils.lines_from_file("input/" .. day .. ".test.txt")

solver.init(input, test_input)
local results = solver.run()

if results[1] then
    print("Part One: " .. results[1])
else
    print("Either the test for part one failed, or the solution return nil.")
end

if results[2] then
    print("Part Two: " .. results[2])
else
    print("Either the test for part two failed, or the solution return nil.")
end