/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/ian/code/nim/fizzbuzz/src/nimcache/nim_nim.o /home/ian/code/nim/fizzbuzz/src/nimcache/nim_nim.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_QeWl6B6ffS4pU6WWrtcrDw tyTuple_QeWl6B6ffS4pU6WWrtcrDw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
typedef tyTuple_QeWl6B6ffS4pU6WWrtcrDw tyArray_Sodm2OIr4dRjCxokFiMY3g[3];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkSound_tCc9bHJlGOmU7X4QMjmVIYw)(NI i, NI n);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_xOfksDa5lOpfO1acT4wYQg_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_xOfksDa5lOpfO1acT4wYQg_9)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_NIMCALL(void, TM_xOfksDa5lOpfO1acT4wYQg_11)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, nimDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyArray_Sodm2OIr4dRjCxokFiMY3g sounds_oeBbg8Jc5O8CaG9cF3nVs0Q;
TNimType NTI_QeWl6B6ffS4pU6WWrtcrDw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_Sodm2OIr4dRjCxokFiMY3g_;
NI i_NcMHkdZRD0JZT1dva3sh5Q;
NimStringDesc* output_9bZTR3hEGnnp5GjWneqrzNA;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_BOOL a_sound_Sdspcry8ybTtDPPjm6iyxA;
tyTuple_QeWl6B6ffS4pU6WWrtcrDw sound_TnUf9cfSAnD9aJoBGvBGkBVQ;
STRING_LITERAL(TM_xOfksDa5lOpfO1acT4wYQg_6, "Fizz", 4);
STRING_LITERAL(TM_xOfksDa5lOpfO1acT4wYQg_7, "Buzz", 4);
STRING_LITERAL(TM_xOfksDa5lOpfO1acT4wYQg_8, "Bazz", 4);
NIM_CONST tyArray_Sodm2OIr4dRjCxokFiMY3g TM_xOfksDa5lOpfO1acT4wYQg_5 = {{((NI) 3),
((NimStringDesc*) &TM_xOfksDa5lOpfO1acT4wYQg_6)}
,
{((NI) 5),
((NimStringDesc*) &TM_xOfksDa5lOpfO1acT4wYQg_7)}
,
{((NI) 7),
((NimStringDesc*) &TM_xOfksDa5lOpfO1acT4wYQg_8)}
}
;
STRING_LITERAL(TM_xOfksDa5lOpfO1acT4wYQg_10, "", 0);

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkSound_tCc9bHJlGOmU7X4QMjmVIYw)(NI i, NI n) {
	NIM_BOOL result;
	nimfr_("checkSound", "nim.nim");
{	result = (NIM_BOOL)0;
	nimln_(4, "nim.nim");
	{
		NI TM_xOfksDa5lOpfO1acT4wYQg_2;
		TM_xOfksDa5lOpfO1acT4wYQg_2 = modInt(i, n);
		if (!((NI)(TM_xOfksDa5lOpfO1acT4wYQg_2) == ((NI) 0))) goto LA3_;
		nimln_(5, "nim.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(7, "nim.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_xOfksDa5lOpfO1acT4wYQg_4)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 3; T1_++) {
	nimGCvisit((void*)sounds_oeBbg8Jc5O8CaG9cF3nVs0Q[T1_].Field1, 0);
	}
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_xOfksDa5lOpfO1acT4wYQg_9)(void) {
	nimGCvisit((void*)output_9bZTR3hEGnnp5GjWneqrzNA, 0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_xOfksDa5lOpfO1acT4wYQg_11)(void) {
	nimGCvisit((void*)sound_TnUf9cfSAnD9aJoBGvBGkBVQ.Field1, 0);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	nimDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("nim", "nim.nim");
nimRegisterGlobalMarker(TM_xOfksDa5lOpfO1acT4wYQg_4);
nimRegisterGlobalMarker(TM_xOfksDa5lOpfO1acT4wYQg_9);
nimRegisterGlobalMarker(TM_xOfksDa5lOpfO1acT4wYQg_11);
	nimln_(9, "nim.nim");
	genericAssign((void*)sounds_oeBbg8Jc5O8CaG9cF3nVs0Q, (void*)TM_xOfksDa5lOpfO1acT4wYQg_5, (&NTI_Sodm2OIr4dRjCxokFiMY3g_));
	{
		NI res;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NimStringDesc* T4_;
				NI TM_xOfksDa5lOpfO1acT4wYQg_13;
				if (!(res <= ((NI) 100))) goto LA3;
				nimln_(2047, "system.nim");
				i_NcMHkdZRD0JZT1dva3sh5Q = res;
				asgnRefNoCycle((void**) (&output_9bZTR3hEGnnp5GjWneqrzNA), NIM_NIL);
				nimln_(16, "nim.nim");
				T4_ = (NimStringDesc*)0;
				T4_ = output_9bZTR3hEGnnp5GjWneqrzNA; output_9bZTR3hEGnnp5GjWneqrzNA = copyStringRC1(((NimStringDesc*) &TM_xOfksDa5lOpfO1acT4wYQg_10));
				if (T4_) nimGCunrefNoCycle(T4_);
				a_sound_Sdspcry8ybTtDPPjm6iyxA = 0;
				nimln_(17, "nim.nim");
				a_sound_Sdspcry8ybTtDPPjm6iyxA = NIM_FALSE;
				{
					NI i;
					chckNil((void*)(&sound_TnUf9cfSAnD9aJoBGvBGkBVQ));
					genericReset((void*)(&sound_TnUf9cfSAnD9aJoBGvBGkBVQ), (&NTI_QeWl6B6ffS4pU6WWrtcrDw_));
					nimln_(2199, "system.nim");
					i = ((NI) 0);
					nimln_(2200, "system.nim");
					{
						if (!(((NI) (i)) <= ((NI) 2))) goto LA8_;
						{
							nimln_(2201, "system.nim");
							while (1) {
								NimStringDesc* T12_;
								NI TM_xOfksDa5lOpfO1acT4wYQg_12;
								nimln_(2202, "system.nim");
								sound_TnUf9cfSAnD9aJoBGvBGkBVQ.Field0 = sounds_oeBbg8Jc5O8CaG9cF3nVs0Q[(i)- 0].Field0;
								T12_ = (NimStringDesc*)0;
								T12_ = sound_TnUf9cfSAnD9aJoBGvBGkBVQ.Field1; sound_TnUf9cfSAnD9aJoBGvBGkBVQ.Field1 = copyStringRC1(sounds_oeBbg8Jc5O8CaG9cF3nVs0Q[(i)- 0].Field1);
								if (T12_) nimGCunrefNoCycle(T12_);
								nimln_(19, "nim.nim");
								{
									NIM_BOOL T15_;
									NimStringDesc* T18_;
									T15_ = (NIM_BOOL)0;
									T15_ = checkSound_tCc9bHJlGOmU7X4QMjmVIYw(i_NcMHkdZRD0JZT1dva3sh5Q, sound_TnUf9cfSAnD9aJoBGvBGkBVQ.Field0);
									if (!T15_) goto LA16_;
									nimln_(20, "nim.nim");
									T18_ = (NimStringDesc*)0;
									T18_ = rawNewString(output_9bZTR3hEGnnp5GjWneqrzNA->Sup.len + sound_TnUf9cfSAnD9aJoBGvBGkBVQ.Field1->Sup.len + 0);
appendString(T18_, output_9bZTR3hEGnnp5GjWneqrzNA);
appendString(T18_, sound_TnUf9cfSAnD9aJoBGvBGkBVQ.Field1);
									asgnRefNoCycle((void**) (&output_9bZTR3hEGnnp5GjWneqrzNA), T18_);
									nimln_(21, "nim.nim");
									a_sound_Sdspcry8ybTtDPPjm6iyxA = NIM_TRUE;
								}
								LA16_: ;
								nimln_(2203, "system.nim");
								{
									if (!(((NI) 2) <= ((NI) (i)))) goto LA21_;
									goto LA10;
								}
								LA21_: ;
								nimln_(2204, "system.nim");
								TM_xOfksDa5lOpfO1acT4wYQg_12 = addInt(i, ((NI) 1));
								if (TM_xOfksDa5lOpfO1acT4wYQg_12 < 0 || TM_xOfksDa5lOpfO1acT4wYQg_12 > 2) raiseOverflow();
								i = (NI)(TM_xOfksDa5lOpfO1acT4wYQg_12);
							}
						} LA10: ;
					}
					LA8_: ;
				}
				nimln_(22, "nim.nim");
				{
					tyArray_nHXaesL0DJZHyVS07ARPRA T27_;
					if (!a_sound_Sdspcry8ybTtDPPjm6iyxA) goto LA25_;
					nimln_(23, "nim.nim");
					memset((void*)T27_, 0, sizeof(T27_));
					T27_[0] = copyString(output_9bZTR3hEGnnp5GjWneqrzNA);
					echoBinSafe(T27_, 1);
				}
				goto LA23_;
				LA25_: ;
				{
					tyArray_nHXaesL0DJZHyVS07ARPRA T29_;
					nimln_(25, "nim.nim");
					memset((void*)T29_, 0, sizeof(T29_));
					T29_[0] = nimIntToStr(i_NcMHkdZRD0JZT1dva3sh5Q);
					echoBinSafe(T29_, 1);
				}
				LA23_: ;
				nimln_(2048, "system.nim");
				TM_xOfksDa5lOpfO1acT4wYQg_13 = addInt(res, ((NI) 1));
				res = (NI)(TM_xOfksDa5lOpfO1acT4wYQg_13);
			} LA3: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimDatInit000)(void) {
static TNimNode* TM_xOfksDa5lOpfO1acT4wYQg_3[2];
static TNimNode TM_xOfksDa5lOpfO1acT4wYQg_0[3];
NTI_QeWl6B6ffS4pU6WWrtcrDw_.size = sizeof(tyTuple_QeWl6B6ffS4pU6WWrtcrDw);
NTI_QeWl6B6ffS4pU6WWrtcrDw_.kind = 18;
NTI_QeWl6B6ffS4pU6WWrtcrDw_.base = 0;
NTI_QeWl6B6ffS4pU6WWrtcrDw_.flags = 2;
TM_xOfksDa5lOpfO1acT4wYQg_3[0] = &TM_xOfksDa5lOpfO1acT4wYQg_0[1];
TM_xOfksDa5lOpfO1acT4wYQg_0[1].kind = 1;
TM_xOfksDa5lOpfO1acT4wYQg_0[1].offset = offsetof(tyTuple_QeWl6B6ffS4pU6WWrtcrDw, Field0);
TM_xOfksDa5lOpfO1acT4wYQg_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_xOfksDa5lOpfO1acT4wYQg_0[1].name = "Field0";
TM_xOfksDa5lOpfO1acT4wYQg_3[1] = &TM_xOfksDa5lOpfO1acT4wYQg_0[2];
TM_xOfksDa5lOpfO1acT4wYQg_0[2].kind = 1;
TM_xOfksDa5lOpfO1acT4wYQg_0[2].offset = offsetof(tyTuple_QeWl6B6ffS4pU6WWrtcrDw, Field1);
TM_xOfksDa5lOpfO1acT4wYQg_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_xOfksDa5lOpfO1acT4wYQg_0[2].name = "Field1";
TM_xOfksDa5lOpfO1acT4wYQg_0[0].len = 2; TM_xOfksDa5lOpfO1acT4wYQg_0[0].kind = 2; TM_xOfksDa5lOpfO1acT4wYQg_0[0].sons = &TM_xOfksDa5lOpfO1acT4wYQg_3[0];
NTI_QeWl6B6ffS4pU6WWrtcrDw_.node = &TM_xOfksDa5lOpfO1acT4wYQg_0[0];
NTI_Sodm2OIr4dRjCxokFiMY3g_.size = sizeof(tyArray_Sodm2OIr4dRjCxokFiMY3g);
NTI_Sodm2OIr4dRjCxokFiMY3g_.kind = 16;
NTI_Sodm2OIr4dRjCxokFiMY3g_.base = (&NTI_QeWl6B6ffS4pU6WWrtcrDw_);
NTI_Sodm2OIr4dRjCxokFiMY3g_.flags = 2;
}

